import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import LoadingWrapper from "@/components/LoadingWrapper"; // New Client Wrapper
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar"

import {
  NavigationMenu,
  NavigationMenuItem,
  NavigationMenuList,
  NavigationMenuLink,
} from "@/components/ui/navigation-menu"; // Ensure correct path

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <LoadingWrapper> {/* Wrap the content in a client-side loader */}
          {/* Navigation Bar */}
          <nav className="navbar p-4 border-b flex items-center justify-between">
            {/* Left Side - Navigation Menu */}
            <NavigationMenu>
              <NavigationMenuList>
                <NavigationMenuItem>
                  <NavigationMenuLink href="/">Home</NavigationMenuLink>
                </NavigationMenuItem>
                <NavigationMenuItem>
                  <NavigationMenuLink href="/resume">Resume</NavigationMenuLink>
                </NavigationMenuItem>
                <NavigationMenuItem>
                  <NavigationMenuLink href="/contact">Contact</NavigationMenuLink>
                </NavigationMenuItem>
              </NavigationMenuList>
            </NavigationMenu>

            {/* Right Side - Avatar */}
            <Avatar className="w-10 h-10 border">
              <AvatarImage src="https://i.imgur.com/snkIT8W.jpeg" />
              <AvatarFallback>CN</AvatarFallback>
            </Avatar>
          </nav>

          {/* Page Content */}
          {children}
        </LoadingWrapper>
      </body>
    </html>
  );
}
