import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {
  NavigationMenu,
  NavigationMenuContent,
  NavigationMenuIndicator,
  NavigationMenuItem,
  NavigationMenuLink,
  NavigationMenuList,
  NavigationMenuTrigger,
  NavigationMenuViewport,
} from "@/components/ui/navigation-menu"

import { Progress } from "@/components/ui/progress"
import Link from "next/link";




const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};




export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >

        <NavigationMenu>
        <NavigationMenuList>
        
          <NavigationMenuItem>
            <NavigationMenuTrigger>
              About Me
            </NavigationMenuTrigger>
            <NavigationMenuContent>
              <NavigationMenuLink href = "/"> Home</NavigationMenuLink>
            </NavigationMenuContent>
          </NavigationMenuItem>

          <NavigationMenuItem>
            <NavigationMenuTrigger>
              Resume
            </NavigationMenuTrigger>
            <NavigationMenuContent>
              <NavigationMenuLink href = "/resume">Resume</NavigationMenuLink>
            </NavigationMenuContent>
          </NavigationMenuItem>

          <NavigationMenuItem>
            <NavigationMenuTrigger>
              Contact
            </NavigationMenuTrigger>
            <NavigationMenuContent>
              <NavigationMenuLink href = "/contact">Contact</NavigationMenuLink>
            </NavigationMenuContent>
          </NavigationMenuItem>

        </NavigationMenuList>
      </NavigationMenu>

        {children}

      </body>
    </html>
  );
}
